sudo: required
services:
  - docker

before_install:
  - docker build -t mwiesbau/flask-tdd-docker -f Dockerfile.prod .

script:
  - docker container run -e CI=true -n flask-tdd mwiesbau/flask-tdd-docker pytest "project/tests" -p no:warnings